### ISSUE TITLE
Allow for lower than u32 type to lower memory consumption

### ISSUE THREAD

**Issue by Hoohm** [ion-elgreco/polars-distance#12]
At the moment all functions return u32 types.
It would allow me to reduce memory consumption by using u8 and u16.
Could be defaulting to the type fitting the maximum string length.

**Comment by ion-elgreco** [comment]
@Hoohm I can only change the return type after I know the max length of a Series/ChunkedArray, I could shrink the dtype but I rather provide a consistent dtype as return type. 

I suggest you execute `pl.col().shrink_dtype` yourself, see docs here: https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.shrink_dtype.html

**Comment by Hoohm** [comment]
I understand. I'll use the tip, thank you.
