### ISSUE TITLE
Deprecation warning - `polars.type_aliases` module is deprecated

### ISSUE THREAD

**Issue by chris-park** [ion-elgreco/polars-distance#22]
# OS
Windows 11

# Python version
3.12.4

# Package versions
* `polars==1.5.0`
* `polars-distance==0.4.3`

# Issue
I get the following deprecation warning when I first import the `polars_distance` package in Python:
> DeprecationWarning: The `polars.type_aliases` module is deprecated. The type aliases have moved to the `polars._typing` module to explicitly mark them as private. Please define your own type aliases, or temporarily import from the `polars._typing` module. A public `polars.typing` module will be added in the future.

**Comment by ion-elgreco** [comment]
@chris-park could you open a PR to resolve that?
