### ISSUE TITLE
Leftover `dbg` in hamming distance, resulting in stdout overflow

### ISSUE THREAD

**Issue by marinegor** [ion-elgreco/polars-distance#27]
Hi, this line:

https://github.com/ion-elgreco/polars-distance/blob/40cd9bdd45f6c27111075788d94f805819170026/polars_distance/src/string.rs#L9

probably shouldn't be there?

I see this:

![image](https://github.com/user-attachments/assets/bca77709-4f10-413e-b909-a4590fad7738)

when I calculate the hamming distance on the dataframe with 10 rows (and can't really do it for larger dataframes because the jupyter hangs)

**Comment by ion-elgreco** [comment]
@marinegor could you make a PR to address it?
